# Archivo de configuraci贸n para Nixpacks (Versi贸n Correcta y Unificada)

[variables]
# Soluci贸n #2: Forzamos el valor de ALLOWED_HOSTNAMES con las comillas correctas para evitar el error de JSON.
ALLOWED_HOSTNAMES = '"cal.amai.solutions"'

[phases.build]
# Soluci贸n #1: Usamos "npx turbo run build" para construir solo la app web y sus dependencias, evitando los paquetes con errores.
cmds = ["npx turbo run build --filter=@calcom/web"]
